## Problem One: Matrix product is calculated manually

Given matrices:  

$ A = \left [\begin {matrix} -1 & 2 & 3 \\ 4 & -5 & 6 \\ 7 & 8 & -9 \end{matrix} \right]$, $B = \left [\begin {matrix} 0 & 2 & 1 \\ 0 & 2 & -8 \\ 2 & 9 & -1 \end {matrix} \right]$  

To solve the above matrix problem by hand, I followed the following steps:  
i. I ensured that the number of columns of the first matrix is equal to the number of rows in the second matrix. In this case, 3 = 3.  

ii. Associating the subscripts i and j with the index of the rows and columns respectively, to calculate the $i^{th}$ row and $i^{th}$ column of the resulting matrix \(AB\), I used the formula:

$(AB)_{ij} = A_{i1}B_{1j} + A_{i2}B_{2j} + A_{i3}B_{3j}$

iii. I computed each element:

1. $ (AB)_{11} = (-1)(0) + (2)(0) + (3)(2) = 6 $
2. $ (AB)_{12} = (-1)(2) + (2)(2) + (3)(9) = 29 $
3. $ (AB)_{13} = (-1)(1) + (2)(-8) + (3)(-1) = -20 $

The first row of \(AB\) is \([6, 29, -20]\).

Continuing this process for the remaining rows and columns:

4. $ (AB)_{21} = (4)(0) + (-5)(0) + (6)(2) = 12 $
5. $ (AB)_{22} = (4)(2) + (-5)(2) + (6)(9) = 52 $
6. $ (AB)_{23} = (4)(1) + (-5)(-8) + (6)(-1) = 38 $

The second row of \(AB\) is \([12, 52, 38]\).

7. $(AB)_{31} = (7)(0) + (8)(0) + (-9)(2) = -18 $
8. $(AB)_{32} = (7)(2) + (8)(2) + (-9)(9) = -51 $
9. $(AB)_{33} = (7)(1) + (8)(-8) + (-9)(-1) = -48 $

The third row of \(AB\) is \([-18, -51, -48]\).

iv. I created a new matrix with the resultant rows from the calculations above.

So, the matrix product \(AB\) is:

$$AB = \left[\begin{array}{ccc} 6 & 29 & -20 \\ 12 & 52 & 38 \\ -18 & -51 & -48 \end{array}\right]$$

## Problem Two: Calculation by NumPy function

In [1]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

In [2]:
# calculating the matrix product using np.dot()
np.dot(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [3]:
# calculating the matrix product using np.matmul()
np.matmul(a_ndarray, b_ndarray)

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

In [4]:
# calculating the matrix product using @
a_ndarray @ b_ndarray

array([[  6,  29, -20],
       [ 12,  52,  38],
       [-18, -51, -48]])

## Problem Three: Implementation of calculation of a certain element

In [5]:
# Performing matrix multiplication on a certain element without using np.matmul(), np.dot() or @ operators.


certain_element = 0
for k in range(3):
    certain_element += a_ndarray[0,k] * b_ndarray[k,0]
    
print(certain_element)

6


## Problem Four: Creating a function that performs matrix multiplication

In [6]:
# Function that performs matrix multiplications


def compute_matmul(A, B):
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must be equal to the number of rows in B")
        
    c_ndarray = np.zeros((len(A),len(B[0])), dtype=np.int64)
    
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(A[0])):
                c_ndarray[i,j] += A[i,k] * B[k,j]
    return c_ndarray

print(compute_matmul(a_ndarray, b_ndarray))

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


## Problem Five: Judge the input whose calculation is not defined

In [7]:
d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])


# using an if statement to display the problem in the input form using print()


def compute_matmul(A, B):
    if not(isinstance(A, list) or isinstance(A, np.ndarray)):
        print(f"expected a list or numpy.ndarray from arg1 but recieved {type(A)}")
        return ""
    if not(isinstance(B, list) or isinstance(B, np.ndarray)):
        print(f"expected a list or numpy.ndarray from arg1 but recieved {type(B)}")
        return ""
        
    if len(A[0]) != len(B):
        raise ValueError("Number of columns in A must be equal to the number of rows in B")
        
    c_ndarray = np.zeros((len(A),len(B[0])), dtype=np.int64)
    
    
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(A[0])):
                c_ndarray[i,j] += A[i,k] * B[k,j]
    return c_ndarray


# Checking that the function catches some edge cases 
print(compute_matmul(d_ndarray, e_ndarray))

ValueError: Number of columns in A must be equal to the number of rows in B

## Problem Six: Transposition

In [ ]:
# transposing e_ndarray matrix to make the matrices compatible for matrix multiplication

compute_matmul(d_ndarray, e_ndarray.transpose())